server:
  port: 8082
spring:
  dubbo:
    # dubbo 中的服务名称
    application: user-web
    # dubbo 的通讯协议名称
    protocol:
      name: dubbo
    registry:
      # zookeeper注册中心的地址
      address: 192.168.169.3:2181
      # zookeeper的通讯协议的名称
      protocol: zookeeper
    # dubbo的服务的扫描路径
    base-package: com.lin.mall
logging:
  level:
    com.lin: debug